---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - list
  - watch
- apiGroups:
  - panoptium.io
  resources:
  - agentclusterpolicies
  - agentpolicies
  - agentprofiles
  - agentquarantines
  - threatsignatures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - panoptium.io
  resources:
  - agentclusterpolicies/finalizers
  - agentpolicies/finalizers
  - agentprofiles/finalizers
  - agentquarantines/finalizers
  - threatsignatures/finalizers
  verbs:
  - update
- apiGroups:
  - panoptium.io
  resources:
  - agentclusterpolicies/status
  - agentpolicies/status
  - agentprofiles/status
  - agentquarantines/status
  - threatsignatures/status
  verbs:
  - get
  - patch
  - update
