{{- if .Values.extproc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "panoptium.fullname" . }}-controller-manager-extproc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panoptium.labels" . | nindent 4 }}
    app.kubernetes.io/component: extproc
spec:
  ports:
    - port: {{ .Values.extproc.port }}
      targetPort: {{ .Values.extproc.port }}
      protocol: TCP
      name: grpc
      appProtocol: kubernetes.io/h2c
  selector:
    {{- include "panoptium.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
{{- end }}
